### PR TITLE
fix not working with @strapi/plugin-users-permissions 4.1.8 and above

### PR DESCRIPTION
**Pull request by htdangkhoa**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

fix not working with `@strapi/plugin-users-permissions` version `4.1.8` and above: 
- `strapi.service("plugin::users-permissions.role").find` is not a function
- `strapi.service("plugin::users-permissions.role").findOne` is not a function

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Review by roelbeerens — COMMENTED** [review]
Thanks for the effort, but unfortunately this has already been fixed in version 1.0.4. Strapi decided to rename these functions somewhere around Strapi v4.2.x. In order to work with Strapi lower than v4.2 you should set the version of the package to 1.0.3. That version has your changes in it 😉
